<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevRecall.Application\DevRecall.Application.csproj" />
    <ProjectReference Include="..\DevRecall.Domain\DevRecall.Domain.csproj" />
  </ItemGroup>

</Project>
