<script setup lang="ts">
import type { PagedResponse } from '~/types/api'; import type { DueReviewItem, ReviewEvaluation } from '~/types/domain'
definePageMeta({ layout: 'focus' }); useSeoMeta({ title: 'Review session' }); const api = useApi(); const queue = ref<DueReviewItem[]>([]); const index = ref(0); const revealed = ref(false); const loading = ref(true); const evaluating = ref(false); const result = ref<ReviewEvaluation>(); const current = computed(() => queue.value[index.value])
async function load() { loading.value = true; try { queue.value = (await api.get<PagedResponse<DueReviewItem>>('/review-items/due', { page: 1, pageSize: 50 })).items } finally { loading.value = false } }
async function evaluate(evaluation: string) { if (!current.value || !revealed.value || evaluating.value) return; evaluating.value = true; try { result.value = await api.post<ReviewEvaluation>(`/review-items/${current.value.reviewItemId}/evaluate`, { evaluation, expectedReviewCount: current.value.reviewCount }); setTimeout(() => { index.value++; revealed.value = false; result.value = undefined }, 650) } finally { evaluating.value = false } }
function onKey(event: KeyboardEvent) { if (event.code === 'Space') { event.preventDefault(); revealed.value = true } if (revealed.value && ['1','2','3','4'].includes(event.key)) evaluate(['Again','Hard','Good','Easy'][Number(event.key)-1]!) }
onMounted(() => { load(); window.addEventListener('keydown', onKey) }); onBeforeUnmount(() => window.removeEventListener('keydown', onKey))
</script>
<template><section class="review-session"><CoreLoadingState v-if="loading" label="Preparing reviews" /><CoreEmptyState v-else-if="!current" title="Review complete" description="You have finished this due queue." icon="i-lucide-party-popper"><UButton to="/app/today" label="Return to Today" /></CoreEmptyState><template v-else><header><span>Review {{ index + 1 }} of {{ queue.length }}</span><UButton to="/app/review" label="Exit" color="neutral" variant="ghost" /></header><div class="progress"><span :style="{ width: `${(index / queue.length) * 100}%` }" /></div><article><CoreStatusBadge :value="current.resourceType" /><h1>{{ current.resourceTitle }}</h1><p>{{ current.resourcePreview || 'Recall the most important details before revealing the saved context.' }}</p><button v-if="!revealed" class="reveal" @click="revealed = true"><UIcon name="i-lucide-eye" /> Reveal context <kbd>Space</kbd></button><div v-else class="answer"><p>{{ current.resourcePreview || 'Use your own notes to verify the answer.' }}</p><small>Previous interval: {{ current.intervalDays }} days</small></div></article><p v-if="result" class="feedback">Next review in {{ result.nextIntervalDays }} days.</p><div class="ratings" :aria-disabled="!revealed"><UButton v-for="(rating, ratingIndex) in ['Again','Hard','Good','Easy']" :key="rating" :disabled="!revealed || evaluating" :color="rating === 'Again' ? 'error' : rating === 'Hard' ? 'warning' : rating === 'Easy' ? 'success' : 'primary'" variant="soft" @click="evaluate(rating)"><kbd>{{ ratingIndex + 1 }}</kbd>{{ rating }}</UButton></div></template></section></template>
<style scoped>.review-session header { display: flex; align-items: center; justify-content: space-between; color: var(--ui-text-muted); }.progress { height: .3rem; margin: .75rem 0 4rem; border-radius: 1rem; background: var(--ui-bg-muted); overflow: hidden; }.progress span { display: block; height: 100%; background: var(--ui-primary); transition: width .2s; }.review-session article { display: grid; justify-items: center; gap: 1.25rem; text-align: center; }.review-session h1 { max-width: 24ch; font-size: clamp(1.8rem, 5vw, 3rem); font-weight: 750; line-height: 1.15; }.review-session article > p { max-width: 44rem; color: var(--ui-text-muted); font-size: 1.05rem; }.reveal { display: flex; align-items: center; gap: .6rem; margin-top: 2rem; padding: .8rem 1.1rem; border: 1px solid var(--ui-border); border-radius: .7rem; background: var(--ui-bg-elevated); }.answer { width: min(100%, 44rem); padding: 1.25rem; border: 1px solid var(--ui-border); border-radius: .8rem; background: var(--ui-bg-muted); }.answer small { display: block; margin-top: .75rem; color: var(--ui-text-muted); }.ratings { display: grid; grid-template-columns: repeat(4, 1fr); gap: .6rem; margin: 2rem auto 0; }.ratings kbd { margin-right: .35rem; }.feedback { margin-top: 1rem; text-align: center; color: var(--ui-success); }@media (max-width: 600px) { .ratings { grid-template-columns: repeat(2, 1fr); }.progress { margin-bottom: 2rem; } }</style>
