using DevRecall.Application.Analytics;
using DevRecall.Application.Analytics.DailyActivity;
using DevRecall.Application.Analytics.DsaPerformance;
using DevRecall.Application.Analytics.Insights;
using DevRecall.Application.Analytics.ModuleBreakdown;
using DevRecall.Application.Analytics.Overview;
using DevRecall.Application.Analytics.ReviewPerformance;
using DevRecall.Application.Dsa.Archive;
using DevRecall.Application.Dsa.Attempts.Compare;
using DevRecall.Application.Dsa.Attempts.Create;
using DevRecall.Application.Dsa.Attempts.GetDetail;
using DevRecall.Application.Dsa.Attempts.GetLatestSuccessful;
using DevRecall.Application.Dsa.Attempts.GetList;
using DevRecall.Application.Dsa.Create;
using DevRecall.Application.Dsa.GetDetail;
using DevRecall.Application.Dsa.GetList;
using DevRecall.Application.Dsa.Practice;
using DevRecall.Application.Dsa.Update;
using DevRecall.Application.Identity.GetCurrentUser;
using DevRecall.Application.Identity.Login;
using DevRecall.Application.Identity.Onboarding;
using DevRecall.Application.Identity.Register;
using DevRecall.Application.Interview.Answers.CreateDraft;
using DevRecall.Application.Interview.Answers.Publish;
using DevRecall.Application.Interview.Answers.UpdateDraft;
using DevRecall.Application.Interview.Archive;
using DevRecall.Application.Interview.Create;
using DevRecall.Application.Interview.FollowUps;
using DevRecall.Application.Interview.GetDetail;
using DevRecall.Application.Interview.GetList;
using DevRecall.Application.Interview.Practice;
using DevRecall.Application.Interview.Update;
using DevRecall.Application.Knowledge.Archive;
using DevRecall.Application.Knowledge.ChangePosition;
using DevRecall.Application.Knowledge.Create;
using DevRecall.Application.Knowledge.GetByTags;
using DevRecall.Application.Knowledge.GetDetail;
using DevRecall.Application.Knowledge.GetTree;
using DevRecall.Application.Knowledge.Move;
using DevRecall.Application.Knowledge.Reorder;
using DevRecall.Application.Knowledge.Tags.Archive;
using DevRecall.Application.Knowledge.Tags.Assign;
using DevRecall.Application.Knowledge.Tags.Create;
using DevRecall.Application.Knowledge.Tags.GetList;
using DevRecall.Application.Knowledge.Tags.Remove;
using DevRecall.Application.Knowledge.Tags.Rename;
using DevRecall.Application.Knowledge.Update;
using DevRecall.Application.Knowledge.UpdateContent;
using DevRecall.Application.Knowledge.UpdateMetadata;
using DevRecall.Application.Knowledge.Workspace;
using DevRecall.Application.Navigation;
using DevRecall.Application.Recommendations.Generation;
using DevRecall.Application.Recommendations.GetDetail;
using DevRecall.Application.Recommendations.GetList;
using DevRecall.Application.Recommendations.Lifecycle;
using DevRecall.Application.Recommendations.Synchronize;
using DevRecall.Application.Reviews.Create;
using DevRecall.Application.Reviews.Evaluate;
using DevRecall.Application.Reviews.GetDetail;
using DevRecall.Application.Reviews.GetDue;
using DevRecall.Application.Reviews.GetHistory;
using DevRecall.Application.Search;
using DevRecall.Application.Study.Cancel;
using DevRecall.Application.Study.Complete;
using DevRecall.Application.Study.Create;
using DevRecall.Application.Study.GetDetail;
using DevRecall.Application.Study.GetList;
using DevRecall.Application.Study.Items.Add;
using DevRecall.Application.Study.Items.Complete;
using DevRecall.Application.Study.Items.Remove;
using DevRecall.Application.Study.Items.Reorder;
using DevRecall.Application.Study.Items.Skip;
using DevRecall.Application.Study.Items.Start;
using DevRecall.Application.Study.Reflection;
using DevRecall.Application.Study.Start;
using DevRecall.Application.Study.Update;
using DevRecall.Application.StudyPlans.Convert;
using DevRecall.Application.StudyPlans.Generate;
using DevRecall.Application.StudyPlans.GetDetail;
using DevRecall.Application.StudyPlans.GetList;
using DevRecall.Application.StudyPlans.Mutations;
using DevRecall.Application.Today;
using DevRecall.Application.WeakTopics.GetDetail;
using DevRecall.Application.WeakTopics.GetList;
using DevRecall.Application.WeakTopics.Recalculate;
using DevRecall.Application.WeakTopics.RecalculateAll;
using Microsoft.Extensions.DependencyInjection;

namespace DevRecall.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(
        this IServiceCollection services)
    {
        services.AddScoped<CompareDsaAttemptsHandler>();
        services.AddScoped<AnalyticsDateRangeResolver>();
        services.AddScoped<GetDailyActivityHandler>();
        services.AddScoped<GetDsaPerformanceHandler>();
        services.AddScoped<GetModuleBreakdownHandler>();
        services.AddScoped<GetProgressOverviewHandler>();
        services.AddScoped<AnalyticsInsightsHandler>();
        services.AddScoped<GetLearningInsightsHandler>();
        services.AddScoped<GetReviewPerformanceHandler>();
        services.AddScoped<CreateDsaAttemptHandler>();
        services.AddScoped<GetDsaAttemptsHandler>();
        services.AddScoped<GetDsaAttemptDetailHandler>();
        services.AddScoped<GetLatestSuccessfulDsaAttemptHandler>();
        services.AddScoped<ArchiveDsaProblemHandler>();
        services.AddScoped<CreateDsaProblemHandler>();
        services.AddScoped<GetDsaProblemsHandler>();
        services.AddScoped<GetDsaProblemDetailHandler>();
        services.AddScoped<UpdateDsaProblemHandler>();
        services.AddScoped<GetDsaPracticeHandler>();
        services.AddScoped<RegisterUserHandler>();
        services.AddScoped<LoginUserHandler>();
        services.AddScoped<OnboardingHandler>();
        services.AddScoped<GetCurrentUserHandler>();
        services.AddScoped<CreateInterviewQuestionHandler>();
        services.AddScoped<CreateInterviewAnswerDraftHandler>();
        services.AddScoped<PublishInterviewAnswerVersionHandler>();
        services.AddScoped<UpdateInterviewAnswerDraftHandler>();
        services.AddScoped<ArchiveInterviewQuestionHandler>();
        services.AddScoped<GetInterviewQuestionsHandler>();
        services.AddScoped<GetInterviewQuestionDetailHandler>();
        services.AddScoped<UpdateInterviewQuestionHandler>();
        services.AddScoped<CreateInterviewFollowUpHandler>();
        services.AddScoped<GetInterviewFollowUpsHandler>();
        services.AddScoped<UpdateInterviewFollowUpHandler>();
        services.AddScoped<ChangeInterviewFollowUpOrderHandler>();
        services.AddScoped<ArchiveInterviewFollowUpHandler>();
        services.AddScoped<GetInterviewPracticeHandler>();
        services.AddScoped<CompleteInterviewPracticeHandler>();
        services.AddScoped<GetInterviewPracticeHistoryHandler>();
        services.AddScoped<GetInterviewPracticeAttemptHandler>();
        services.AddScoped<CreateKnowledgeNodeHandler>();
        services.AddScoped<GetKnowledgeNodeDetailHandler>();
        services.AddScoped<GetKnowledgeByTagsHandler>();
        services.AddScoped<GetKnowledgeTreeHandler>();
        services.AddScoped<UpdateKnowledgeNodeHandler>();
        services.AddScoped<ArchiveKnowledgeNodeHandler>();
        services.AddScoped<ChangeKnowledgeNodePositionHandler>();
        services.AddScoped<MoveKnowledgeNodeHandler>();
        services.AddScoped<ReorderKnowledgeNodeHandler>();
        services.AddScoped<UpdateKnowledgeContentHandler>();
        services.AddScoped<UpdateKnowledgeMetadataHandler>();
        services.AddScoped<CreateTagHandler>();
        services.AddScoped<GetTagsHandler>();
        services.AddScoped<RenameTagHandler>();
        services.AddScoped<ArchiveTagHandler>();
        services.AddScoped<AssignTagToKnowledgeNodeHandler>();
        services.AddScoped<RemoveTagFromKnowledgeNodeHandler>();
        services.AddScoped<GetKnowledgeListHandler>();
        services.AddScoped<GetKnowledgeDetailHandler>();
        services.AddScoped<GetKnowledgeTopicTreeHandler>();
        services.AddScoped<UpdateKnowledgeHandler>();
        services.AddScoped<DeleteKnowledgeHandler>();
        services.AddScoped<GetKnowledgeTagsHandler>();
        services.AddScoped<CreateKnowledgeTagHandler>();
        services.AddScoped<CreateReviewItemHandler>();
        services.AddScoped<GenerateRecommendationsHandler>();
        services.AddScoped<GetRecommendationsHandler>();
        services.AddScoped<GetRecommendationDetailHandler>();
        services.AddScoped<DismissRecommendationHandler>();
        services.AddScoped<CompleteRecommendationHandler>();
        services.AddScoped<SynchronizeRecommendationsHandler>();
        services.AddScoped<EvaluateReviewItemHandler>();
        services.AddScoped<GetReviewItemDetailHandler>();
        services.AddScoped<GetDueReviewItemsHandler>();
        services.AddScoped<GetReviewHistoryHandler>();
        services.AddScoped<GlobalSearchHandler>();
        services.AddScoped<CreateStudySessionHandler>();
        services.AddScoped<UpdateStudySessionHandler>();
        services.AddScoped<AddStudySessionItemHandler>();
        services.AddScoped<RemoveStudySessionItemHandler>();
        services.AddScoped<ReorderStudySessionItemsHandler>();
        services.AddScoped<StartStudySessionHandler>();
        services.AddScoped<StartStudySessionItemHandler>();
        services.AddScoped<CompleteStudySessionItemHandler>();
        services.AddScoped<SkipStudySessionItemHandler>();
        services.AddScoped<CompleteStudySessionHandler>();
        services.AddScoped<CancelStudySessionHandler>();
        services.AddScoped<GetStudySessionsHandler>();
        services.AddScoped<GetStudySessionDetailHandler>();
        services.AddScoped<UpdateStudySessionReflectionHandler>();
        services.AddScoped<GenerateStudyPlanHandler>();
        services.AddScoped<GetStudyPlansHandler>();
        services.AddScoped<GetStudyPlanDetailHandler>();
        services.AddScoped<UpdateStudyPlanHandler>();
        services.AddScoped<ReplaceStudyPlanDraftHandler>();
        services.AddScoped<UpdateStudyPlanItemHandler>();
        services.AddScoped<RemoveStudyPlanItemHandler>();
        services.AddScoped<ReorderStudyPlanItemsHandler>();
        services.AddScoped<MarkStudyPlanReadyHandler>();
        services.AddScoped<CancelStudyPlanHandler>();
        services.AddScoped<ConvertStudyPlanHandler>();
        services.AddScoped<RecalculateWeakTopicHandler>();
        services.AddScoped<GetWeakTopicsHandler>();
        services.AddScoped<GetWeakTopicDetailHandler>();
        services.AddScoped<RecalculateAllWeakTopicsHandler>();
        services.AddScoped<GetTodayDashboardHandler>();
        services.AddScoped<GetNavigationIndicatorsHandler>();
        services.AddSingleton<ITodayNextActionPolicy, TodayNextActionPolicy>();

        return services;
    }
}
