<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<ProjectReference Include="..\DevRecall.Application\DevRecall.Application.csproj" />
		<ProjectReference Include="..\DevRecall.Contracts\DevRecall.Contracts.csproj" />
		<ProjectReference Include="..\DevRecall.Infrastructure\DevRecall.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.OpenApi" />
	</ItemGroup>

</Project>