export const queryKeys = {
  today: 'today-dashboard',
  navigationIndicators: 'navigation-indicators',
  knowledgeListBase: 'knowledge:list',
  knowledgeList: (canonicalFilters: string) => `knowledge:list:${canonicalFilters}`,
  knowledgeTopics: 'knowledge:topic-tree',
  knowledgeTags: (normalizedQuery = '') => `knowledge:tags:${normalizedQuery.trim().toLowerCase()}`,
  interviewList: 'interview:list',
  interviewQuestion: (id: string) => `interview:question:${id}`,
  interviewPractice: (id: string) => `interview:practice:${id}`,
  interviewAttempts: (id: string, page = 1) => `interview:attempts:${id}:${page}`,
  interviewAttempt: (id: string) => `interview:attempt:${id}`,
  dsaList: 'dsa:list',
  dsaProblem: (id: string) => `dsa:problem:${id}`,
  dsaPractice: (id: string) => `dsa:practice:${id}`,
  dsaAttempts: (id: string, page = 1) => `dsa:attempts:${id}:${page}`,
  dsaAttempt: (id: string) => `dsa:attempt:${id}`,
  reviewDue: 'review:due',
  analyticsOverview: (range: string) => `analytics:overview:${range}`,
  analyticsPerformance: (range: string) => `analytics:performance:${range}`,
  learningInsights: (range: string) => `insights:${range}`,
} as const
