<script setup lang="ts">
import { ApiError } from '~/types/api'; import type { StudySessionDetail, StudySessionDetailItem } from '~/types/domain'; import { formatMinutes } from '~/utils/format'
definePageMeta({ layout: 'app' }); const route = useRoute(); const api = useApi(); const detail = ref<StudySessionDetail>(); const loading = ref(true); const conflict = ref(false); const id = computed(() => String(route.params.id)); useSeoMeta({ title: () => detail.value?.title ?? 'Study session' })
async function load() { loading.value = true; conflict.value = false; try { detail.value = await api.get<StudySessionDetail>(`/study-sessions/${id.value}`) } finally { loading.value = false } }
async function mutate(path: string, body: unknown) { try { await api.post(path, body); await load() } catch (error) { if (error instanceof ApiError && error.problem.status === 409) conflict.value = true; else throw error } }
async function start() { if (detail.value) await mutate(`/study-sessions/${id.value}/start`, { expectedVersion: detail.value.version }) }
async function itemAction(item: StudySessionDetailItem, action: 'start'|'complete'|'skip') { if (detail.value) await mutate(`/study-sessions/${id.value}/items/${item.id}/${action}`, { notes: null, expectedVersion: detail.value.version }) }
async function finish(action: 'complete'|'cancel') { if (detail.value) await mutate(`/study-sessions/${id.value}/${action}`, { expectedVersion: detail.value.version }) }
const current = computed(() => detail.value?.items.find(item => item.status === 'InProgress') ?? detail.value?.items.find(item => item.status === 'Pending')); onMounted(load)
</script>
<template><div><CoreLoadingState v-if="loading" label="Loading study session" /><template v-else-if="detail"><CorePageHeader :title="detail.title" :description="`${formatMinutes(detail.plannedDurationMinutes)} planned · ${detail.progress.completionPercentage}% complete`"><CoreStatusBadge :value="detail.status" /></CorePageHeader><div v-if="conflict" class="conflict"><span>This session changed elsewhere. Reload before continuing.</span><UButton label="Reload" @click="load" /></div><section class="session-grid"><article class="focus-card"><template v-if="detail.status === 'Draft'"><UIcon name="i-lucide-timer" class="hero-icon" /><h2>Ready to focus?</h2><p>{{ detail.items.length }} items are planned for this session.</p><UButton size="lg" label="Start session" icon="i-lucide-play" @click="start" /></template><template v-else-if="current && detail.status === 'InProgress'"><CoreStatusBadge :value="current.resourceType" /><h2>{{ current.resourceTitle }}</h2><p>{{ current.resourcePreview || 'Open the source context and work through this item.' }}</p><div class="focus-actions"><UButton v-if="current.status === 'Pending'" label="Start item" @click="itemAction(current, 'start')" /><template v-else><UButton label="Skip" color="neutral" variant="outline" @click="itemAction(current, 'skip')" /><UButton label="Complete" icon="i-lucide-check" @click="itemAction(current, 'complete')" /></template></div></template><template v-else><UIcon name="i-lucide-circle-check-big" class="hero-icon" /><h2>{{ detail.status === 'Completed' ? 'Session complete' : 'No active item' }}</h2><p>{{ detail.progress.completedItems }} items completed and {{ detail.progress.skippedItems }} skipped.</p><UButton v-if="detail.status === 'InProgress'" label="Complete session" @click="finish('complete')" /></template></article><aside><div class="progress"><span :style="{ width: `${detail.progress.completionPercentage}%` }" /></div><div v-for="item in detail.items" :key="item.id" class="session-item" :class="{ current: item.id === current?.id }"><UIcon :name="item.status === 'Completed' ? 'i-lucide-circle-check' : item.status === 'Skipped' ? 'i-lucide-circle-minus' : item.status === 'InProgress' ? 'i-lucide-play-circle' : 'i-lucide-circle'" /><div><strong>{{ item.resourceTitle }}</strong><small>{{ item.status }}</small></div></div><UButton v-if="['Draft','InProgress'].includes(detail.status)" block label="Cancel session" color="error" variant="ghost" @click="finish('cancel')" /></aside></section></template></div></template>
<style scoped>.conflict { display: flex; justify-content: space-between; align-items: center; gap: 1rem; margin-bottom: 1rem; padding: 1rem; border: 1px solid var(--ui-warning); border-radius: .7rem; }.session-grid { display: grid; grid-template-columns: minmax(0, 1fr) 21rem; gap: 1rem; }.focus-card, .session-grid aside { border: 1px solid var(--ui-border); border-radius: .8rem; }.focus-card { display: grid; min-height: 28rem; place-items: center; align-content: center; gap: 1rem; padding: 2rem; text-align: center; }.focus-card h2 { max-width: 22ch; font-size: 2rem; font-weight: 750; }.focus-card p { max-width: 36rem; color: var(--ui-text-muted); }.hero-icon { font-size: 2.5rem; color: var(--ui-primary); }.focus-actions { display: flex; gap: .5rem; }.session-grid aside { padding: 1rem; }.progress { height: .35rem; margin-bottom: 1rem; overflow: hidden; border-radius: 1rem; background: var(--ui-bg-muted); }.progress span { display: block; height: 100%; background: var(--ui-primary); }.session-item { display: flex; align-items: center; gap: .6rem; padding: .65rem; border-radius: .5rem; color: var(--ui-text-muted); }.session-item.current { background: var(--ui-bg-elevated); color: var(--ui-primary); }.session-item div { display: grid; }.session-item small { font-size: .72rem; }@media (max-width: 760px) { .session-grid { grid-template-columns: 1fr; }.session-grid aside { order: -1; } }</style>
