<script setup lang="ts">
import { ApiError } from '~/types/api'; import type { StudyPlanDetail } from '~/types/domain'; import { formatMinutes } from '~/utils/format'
definePageMeta({ layout: 'app' }); const route = useRoute(); const api = useApi(); const toast = useToast(); const { refreshTodayAndNavigation } = useLearningDataInvalidation(); const detail = ref<StudyPlanDetail>(); const loading = ref(true); const conflict = ref(false); const title = ref(''); const id = computed(() => String(route.params.id)); useSeoMeta({ title: () => detail.value?.title ?? 'Study plan' })
async function load() { loading.value = true; conflict.value = false; try { detail.value = await api.get<StudyPlanDetail>(`/study-plans/${id.value}`); title.value = detail.value.title } finally { loading.value = false } }
async function mutate(work: () => Promise<unknown>) { try { await work(); await load() } catch (error) { if (error instanceof ApiError && error.problem.status === 409) conflict.value = true; else throw error } }
async function saveTitle() { if (!detail.value) return; await mutate(() => api.put(`/study-plans/${id.value}`, { title: title.value, expectedVersion: detail.value!.version })) }
async function duration(itemId: string, minutes: number) { if (!detail.value) return; await mutate(() => api.put(`/study-plans/${id.value}/items/${itemId}`, { plannedDurationMinutes: minutes, expectedVersion: detail.value!.version })) }
async function remove(itemId: string) { if (!detail.value) return; await mutate(() => api.delete(`/study-plans/${id.value}/items/${itemId}`, { expectedVersion: detail.value!.version })) }
async function reorder(index: number, offset: number) { if (!detail.value) return; const items = [...detail.value.items]; const target = index + offset; if (target < 0 || target >= items.length) return; [items[index], items[target]] = [items[target]!, items[index]!]; await mutate(() => api.put(`/study-plans/${id.value}/items/reorder`, { itemIds: items.map(item => item.itemId), expectedVersion: detail.value!.version })) }
async function lifecycle(action: 'ready' | 'cancel') { if (!detail.value) return; await mutate(() => api.post(`/study-plans/${id.value}/${action}`, { expectedVersion: detail.value!.version })); await refreshTodayAndNavigation() }
async function convert() { if (!detail.value) return; const response = await api.post<{ studySessionId: string }>(`/study-plans/${id.value}/convert`, { expectedVersion: detail.value.version }); await refreshTodayAndNavigation(); toast.add({ title: 'Study session created', color: 'success' }); await navigateTo(`/app/study-sessions/${response.studySessionId}`) }
onMounted(load)
</script>
<template><div><CoreLoadingState v-if="loading" label="Loading study plan" /><template v-else-if="detail"><CorePageHeader :title="detail.title" :description="`${detail.itemCount} items · ${formatMinutes(detail.totalPlannedDurationMinutes)}`"><CoreStatusBadge :value="detail.status" /></CorePageHeader><div v-if="conflict" class="conflict" role="alert"><div><strong>This plan changed elsewhere.</strong><p>Reload the latest version before making another change.</p></div><UButton label="Reload" @click="load" /></div><section class="builder"><article><form v-if="detail.status === 'Draft'" class="title-form" @submit.prevent="saveTitle"><UInput v-model="title" class="w-full" /><UButton type="submit" label="Rename" color="neutral" variant="outline" /></form><div class="items"><div v-for="(item, itemIndex) in detail.items" :key="item.itemId" class="plan-item"><span class="handle"><UIcon name="i-lucide-grip-vertical" /></span><div><strong>{{ item.resourceTitle }}</strong><p>{{ item.resourceType }} · {{ item.sourceType }}</p></div><UInput :model-value="item.plannedDurationMinutes" type="number" class="duration" :disabled="detail.status !== 'Draft'" @change="duration(item.itemId, Number(($event.target as HTMLInputElement).value))" /><span>min</span><div v-if="detail.status === 'Draft'" class="item-actions"><button :disabled="itemIndex === 0" @click="reorder(itemIndex, -1)"><UIcon name="i-lucide-chevron-up" /></button><button :disabled="itemIndex === detail.items.length - 1" @click="reorder(itemIndex, 1)"><UIcon name="i-lucide-chevron-down" /></button><button @click="remove(item.itemId)"><UIcon name="i-lucide-trash-2" /></button></div></div></div></article><aside><p>Plan summary</p><strong>{{ formatMinutes(detail.totalPlannedDurationMinutes) }}</strong><span>{{ detail.itemCount }} learning items</span><div v-if="detail.status === 'Draft'"><UButton block label="Mark ready" icon="i-lucide-circle-check" @click="lifecycle('ready')" /><UButton block label="Cancel plan" color="neutral" variant="ghost" @click="lifecycle('cancel')" /></div><UButton v-else-if="detail.status === 'Ready'" block label="Create study session" icon="i-lucide-play" @click="convert" /><UButton v-else-if="detail.convertedStudySessionId" block :to="`/app/study-sessions/${detail.convertedStudySessionId}`" label="Open study session" /></aside></section></template></div></template>
<style scoped>.conflict { display: flex; align-items: center; justify-content: space-between; gap: 1rem; margin-bottom: 1rem; padding: 1rem; border: 1px solid var(--ui-warning); border-radius: .7rem; background: color-mix(in srgb, var(--ui-warning) 8%, transparent); }.conflict p { color: var(--ui-text-muted); }.builder { display: grid; grid-template-columns: minmax(0, 1fr) 18rem; gap: 1rem; align-items: start; }.builder > article, .builder > aside { border: 1px solid var(--ui-border); border-radius: .8rem; }.title-form { display: flex; gap: .5rem; padding: 1rem; border-bottom: 1px solid var(--ui-border); }.items { display: grid; gap: .5rem; padding: 1rem; }.plan-item { display: grid; grid-template-columns: auto minmax(0, 1fr) 5rem auto auto; align-items: center; gap: .5rem; padding: .75rem; border: 1px solid var(--ui-border); border-radius: .6rem; }.handle { color: var(--ui-text-dimmed); }.plan-item p { color: var(--ui-text-muted); font-size: .78rem; }.duration { width: 5rem; }.item-actions { display: flex; }.item-actions button { padding: .3rem; color: var(--ui-text-muted); }.builder aside { position: sticky; top: 5rem; display: grid; gap: .7rem; padding: 1.25rem; }.builder aside > p, .builder aside > span { color: var(--ui-text-muted); }.builder aside > strong { font-size: 2rem; }.builder aside > div { display: grid; gap: .4rem; }@media (max-width: 780px) { .builder { grid-template-columns: 1fr; }.builder aside { position: static; }.plan-item { grid-template-columns: auto minmax(0, 1fr) 4rem auto; }.item-actions { grid-column: 2 / -1; } }</style>
