// <auto-generated />
using System;
using DevRecall.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevRecall.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DevRecallDbContext))]
    [Migration("20260730143402_AddWeakTopicProfiles")]
    partial class AddWeakTopicProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevRecall.Domain.Common.SystemMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_system_metadata");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_system_metadata_key");

                    b.ToTable("system_metadata", (string)null);
                });

            modelBuilder.Entity("DevRecall.Domain.Dsa.Attempts.DsaAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Approach")
                        .HasColumnType("text")
                        .HasColumnName("approach");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DsaProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("dsa_problem_id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<string>("SolutionCode")
                        .HasColumnType("text")
                        .HasColumnName("solution_code");

                    b.Property<string>("SpaceComplexity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("space_complexity");

                    b.Property<string>("TimeComplexity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_complexity");

                    b.HasKey("Id")
                        .HasName("pk_dsa_attempts");

                    b.HasIndex("DsaProblemId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_dsa_attempts_problem_attempt_number");

                    b.HasIndex("DsaProblemId", "AttemptedAtUtc")
                        .HasDatabaseName("ix_dsa_attempts_problem_attempted_at");

                    b.HasIndex("DsaProblemId", "Result", "AttemptNumber")
                        .HasDatabaseName("ix_dsa_attempts_problem_result_number");

                    b.ToTable("dsa_attempts", (string)null);
                });

            modelBuilder.Entity("DevRecall.Domain.Dsa.DsaProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("external_url");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_dsa_problems");

                    b.HasIndex("UserId", "Difficulty", "Status")
                        .HasDatabaseName("ix_dsa_problems_user_difficulty_status");

                    b.HasIndex("UserId", "Source", "Status")
                        .HasDatabaseName("ix_dsa_problems_user_source_status");

                    b.HasIndex("UserId", "Status", "UpdatedAtUtc")
                        .HasDatabaseName("ix_dsa_problems_user_status_updated_at");

                    b.ToTable("dsa_problems", (string)null);
                });

            modelBuilder.Entity("DevRecall.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DevRecall.Domain.Interview.Answers.InterviewAnswerVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("InterviewQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_question_id");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_interview_answer_versions");

                    b.HasIndex("InterviewQuestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_interview_answer_versions_one_draft_per_question")
                        .HasFilter("\"status\" = 1");

                    b.HasIndex("InterviewQuestionId", "Status")
                        .HasDatabaseName("ix_interview_answer_versions_question_status");

                    b.HasIndex("InterviewQuestionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_interview_answer_versions_question_version");

                    b.HasIndex("InterviewQuestionId", "Status", "VersionNumber")
                        .HasDatabaseName("ix_interview_answer_versions_question_status_version");

                    b.ToTable("interview_answer_versions", (string)null);
                });

            modelBuilder.Entity("DevRecall.Domain.Interview.FollowUps.InterviewFollowUpQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("InterviewQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_question_id");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("prompt");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_interview_follow_up_questions");

                    b.HasIndex("InterviewQuestionId", "Status", "SortOrder")
                        .HasDatabaseName("ix_interview_follow_ups_question_status_order");

                    b.ToTable("interview_follow_up_questions", (string)null);
                });

            modelBuilder.Entity("DevRecall.Domain.Interview.InterviewQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_interview_questions");

                    b.HasIndex("UserId", "Difficulty", "Status")
                        .HasDatabaseName("ix_interview_questions_user_difficulty_status");

                    b.HasIndex("UserId", "Status", "UpdatedAtUtc")
                        .HasDatabaseName("ix_interview_questions_user_status_updated_at");

                    b.HasIndex("UserId", "Topic", "Status")
                        .HasDatabaseName("ix_interview_questions_user_topic_status");

                    b.ToTable("interview_questions", (string)null);
                });

            modelBuilder.Entity("DevRecall.Domain.Knowledge.KnowledgeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_nodes");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_knowledge_nodes_parent_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_knowledge_nodes_user_id");

                    b.HasIndex("UserId", "ParentId")
                        .HasDatabaseName("ix_knowledge_nodes_user_id_parent_id");

                    b.HasIndex("UserId", "ParentId", "SortOrder")
                        .HasDatabaseName("ix_knowledge_nodes_user_parent_sort_order");

                    b.ToTable("knowledge_nodes", (string)null);
                });

            modelBuilder.Entity("DevRecall.Domain.Knowledge.Tags.KnowledgeNodeTag", b =>
                {
                    b.Property<Guid>("KnowledgeNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_node_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("KnowledgeNodeId", "TagId")
                        .HasName("pk_knowledge_node_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_knowledge_node_tags_tag_id");

                    b.ToTable("knowledge_node_tags", (string)null);
                });

            modelBuilder.Entity("DevRecall.Domain.Knowledge.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_tags_user_id_normalized_name");

                    b.HasIndex("UserId", "Status", "Name")
                        .HasDatabaseName("ix_tags_user_status_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("DevRecall.Domain.Reviews.ReviewHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Evaluation")
                        .HasColumnType("integer")
                        .HasColumnName("evaluation");

                    b.Property<DateTimeOffset>("NextDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_at_utc");

                    b.Property<int>("NextIntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("next_interval_days");

                    b.Property<DateTimeOffset>("PreviousDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_due_at_utc");

                    b.Property<int>("PreviousIntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("previous_interval_days");

                    b.Property<Guid>("ReviewItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_item_id");

                    b.Property<DateTimeOffset>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_review_histories");

                    b.HasIndex("ReviewItemId", "ReviewedAtUtc")
                        .HasDatabaseName("ix_review_histories_item_reviewed_at");

                    b.ToTable("review_histories", null, t =>
                        {
                            t.HasCheckConstraint("ck_review_histories_next_interval_positive", "next_interval_days > 0");

                            t.HasCheckConstraint("ck_review_histories_previous_interval_non_negative", "previous_interval_days >= 0");
                        });
                });

            modelBuilder.Entity("DevRecall.Domain.Reviews.ReviewItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("interval_days");

                    b.Property<DateTimeOffset?>("LastReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at_utc");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer")
                        .HasColumnName("resource_type");

                    b.Property<int>("ReviewCount")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_review_items");

                    b.HasIndex("UserId", "ResourceType", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_review_items_active_resource")
                        .HasFilter("status = 1");

                    b.HasIndex("UserId", "ResourceType", "Status")
                        .HasDatabaseName("ix_review_items_user_resource_type_status");

                    b.HasIndex("UserId", "Status", "DueAtUtc")
                        .HasDatabaseName("ix_review_items_user_status_due_at");

                    b.ToTable("review_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_review_items_interval_days_non_negative", "interval_days >= 0");

                            t.HasCheckConstraint("ck_review_items_review_count_non_negative", "review_count >= 0");
                        });
                });

            modelBuilder.Entity("DevRecall.Domain.Study.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActualDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("actual_duration_minutes");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PlannedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("planned_duration_minutes");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_study_sessions");

                    b.HasIndex("UserId", "CompletedAtUtc")
                        .HasDatabaseName("ix_study_sessions_user_completed_at");

                    b.HasIndex("UserId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_study_sessions_user_status_created_at");

                    b.ToTable("study_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_study_sessions_actual_duration_non_negative", "actual_duration_minutes IS NULL OR actual_duration_minutes >= 0");

                            t.HasCheckConstraint("ck_study_sessions_planned_duration_non_negative", "planned_duration_minutes >= 0");

                            t.HasCheckConstraint("ck_study_sessions_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("DevRecall.Domain.Study.StudySessionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer")
                        .HasColumnName("resource_type");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StudySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_session_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_study_session_items");

                    b.HasIndex("StudySessionId", "Position")
                        .HasDatabaseName("ix_study_session_items_session_position");

                    b.HasIndex("StudySessionId", "Status")
                        .HasDatabaseName("ix_study_session_items_session_status");

                    b.HasIndex("StudySessionId", "ResourceType", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_study_session_items_session_resource");

                    b.ToTable("study_session_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_study_session_items_position_non_negative", "position >= 0");
                        });
                });

            modelBuilder.Entity("DevRecall.Domain.WeakTopics.WeakTopicProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer")
                        .HasColumnName("resource_type");

                    b.Property<decimal>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("score");

                    b.Property<int>("SignalCount")
                        .HasColumnType("integer")
                        .HasColumnName("signal_count");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_weak_topic_profiles");

                    b.HasIndex("UserId", "CalculatedAtUtc")
                        .HasDatabaseName("ix_weak_topic_profiles_user_calculated_at");

                    b.HasIndex("UserId", "Level", "Score")
                        .HasDatabaseName("ix_weak_topic_profiles_user_level_score");

                    b.HasIndex("UserId", "ResourceType", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_weak_topic_profiles_user_resource");

                    b.ToTable("weak_topic_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_weak_topic_profiles_score_non_negative", "score >= 0");

                            t.HasCheckConstraint("ck_weak_topic_profiles_signal_count_non_negative", "signal_count >= 0");
                        });
                });

            modelBuilder.Entity("DevRecall.Domain.Dsa.Attempts.DsaAttempt", b =>
                {
                    b.HasOne("DevRecall.Domain.Dsa.DsaProblem", null)
                        .WithMany()
                        .HasForeignKey("DsaProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dsa_attempts_dsa_problems_dsa_problem_id");
                });

            modelBuilder.Entity("DevRecall.Domain.Dsa.DsaProblem", b =>
                {
                    b.HasOne("DevRecall.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dsa_problems_users_user_id");

                    b.OwnsMany("DevRecall.Domain.Dsa.DsaProblemTopic", "Topics", b1 =>
                        {
                            b1.Property<Guid>("dsa_problem_id")
                                .HasColumnType("uuid")
                                .HasColumnName("dsa_problem_id");

                            b1.Property<string>("NormalizedName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("dsa_problem_id", "NormalizedName")
                                .HasName("pk_dsa_problem_topics");

                            b1.HasIndex("NormalizedName")
                                .HasDatabaseName("ix_dsa_problem_topics_normalized_name");

                            b1.ToTable("dsa_problem_topics", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("dsa_problem_id")
                                .HasConstraintName("fk_dsa_problem_topics_dsa_problems_dsa_problem_id");
                        });

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("DevRecall.Domain.Interview.Answers.InterviewAnswerVersion", b =>
                {
                    b.HasOne("DevRecall.Domain.Interview.InterviewQuestion", null)
                        .WithMany()
                        .HasForeignKey("InterviewQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_answer_versions_interview_questions_interview_que");
                });

            modelBuilder.Entity("DevRecall.Domain.Interview.FollowUps.InterviewFollowUpQuestion", b =>
                {
                    b.HasOne("DevRecall.Domain.Interview.InterviewQuestion", null)
                        .WithMany()
                        .HasForeignKey("InterviewQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_follow_up_questions_interview_questions_interview");
                });

            modelBuilder.Entity("DevRecall.Domain.Interview.InterviewQuestion", b =>
                {
                    b.HasOne("DevRecall.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_questions_users_user_id");
                });

            modelBuilder.Entity("DevRecall.Domain.Knowledge.KnowledgeNode", b =>
                {
                    b.HasOne("DevRecall.Domain.Knowledge.KnowledgeNode", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_knowledge_nodes_knowledge_nodes_parent_id");

                    b.HasOne("DevRecall.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_nodes_users_user_id");
                });

            modelBuilder.Entity("DevRecall.Domain.Knowledge.Tags.KnowledgeNodeTag", b =>
                {
                    b.HasOne("DevRecall.Domain.Knowledge.KnowledgeNode", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_node_tags_knowledge_nodes_knowledge_node_id");

                    b.HasOne("DevRecall.Domain.Knowledge.Tags.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_node_tags_tags_tag_id");
                });

            modelBuilder.Entity("DevRecall.Domain.Knowledge.Tags.Tag", b =>
                {
                    b.HasOne("DevRecall.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_users_user_id");
                });

            modelBuilder.Entity("DevRecall.Domain.Reviews.ReviewHistory", b =>
                {
                    b.HasOne("DevRecall.Domain.Reviews.ReviewItem", null)
                        .WithMany()
                        .HasForeignKey("ReviewItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_histories_review_items_review_item_id");
                });

            modelBuilder.Entity("DevRecall.Domain.Reviews.ReviewItem", b =>
                {
                    b.HasOne("DevRecall.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_items_users_user_id");
                });

            modelBuilder.Entity("DevRecall.Domain.Study.StudySession", b =>
                {
                    b.HasOne("DevRecall.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_sessions_users_user_id");
                });

            modelBuilder.Entity("DevRecall.Domain.Study.StudySessionItem", b =>
                {
                    b.HasOne("DevRecall.Domain.Study.StudySession", null)
                        .WithMany("Items")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_session_items_study_sessions_study_session_id");
                });

            modelBuilder.Entity("DevRecall.Domain.WeakTopics.WeakTopicProfile", b =>
                {
                    b.HasOne("DevRecall.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weak_topic_profiles_users_user_id");
                });

            modelBuilder.Entity("DevRecall.Domain.Study.StudySession", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
