<script setup lang="ts">
useSeoMeta({ title: 'Developer learning that closes the loop', description: 'Capture technical knowledge, practice recall, schedule reviews, and turn weak topics into a focused study plan.', ogTitle: 'DevRecall — Calm Learning Intelligence', ogDescription: 'A local-first learning OS for developers.' })
</script>

<template>
  <div class="landing">
    <header><NuxtLink to="/" class="brand"><span class="brand-mark" aria-hidden="true">◈</span> DevRecall</NuxtLink><nav><a href="#workflow">How it works</a><a href="#modules">Features</a><UButton to="/login" label="Open app" /></nav></header>
    <main>
      <section class="hero"><UBadge variant="subtle">Calm Learning Intelligence</UBadge><h1>Know what to learn next.</h1><p>DevRecall connects your notes, active recall, interview preparation, DSA practice, spaced repetition, and study plans in one focused loop.</p><div class="hero-actions"><UButton to="/register" size="xl" label="Start locally" trailing-icon="i-lucide-arrow-right" /><UButton to="/login" size="xl" color="neutral" variant="outline" label="Sign in" /></div></section>
      <figure class="product-shot"><img src="/images/devrecall-today-dashboard.png" alt="DevRecall Today workspace showing the next study action, recommendations, and weak topics." width="1294" height="856"><figcaption>The Today workspace turns learning signals into one clear next action.</figcaption></figure>
      <section id="workflow" class="workflow"><div v-for="(step, index) in ['Capture knowledge', 'Practice recall', 'Evaluate performance', 'Schedule review', 'Build the next plan']" :key="step"><span>{{ index + 1 }}</span><strong>{{ step }}</strong></div></section>
      <section id="modules"><p class="eyebrow">One learning system</p><h2>From scattered practice to a repeatable loop.</h2><div class="feature-grid"><article v-for="feature in [{ symbol: '▦', title: 'Knowledge', text: 'Organize durable notes in a connected topic tree.' }, { symbol: '↻', title: 'Review', text: 'Practice a due queue with deterministic spaced repetition.' }, { symbol: '</>', title: 'Interview & DSA', text: 'Improve answers and compare attempts over time.' }, { symbol: '✦', title: 'Plan', text: 'Turn evidence and weak topics into the next best action.' }]" :key="feature.title"><span class="feature-mark" aria-hidden="true">{{ feature.symbol }}</span><h3>{{ feature.title }}</h3><p>{{ feature.text }}</p></article></div></section>
    </main>
    <footer>Built for focused, local-first developer learning.</footer>
  </div>
</template>

<style scoped>
.landing { width: min(100% - 2rem, 76rem); margin: auto; }.landing header { height: 5rem; display: flex; align-items: center; justify-content: space-between; }.brand { display: flex; align-items: center; gap: .5rem; font-weight: 800; }.brand-mark, .feature-mark { color: var(--ui-primary); font-weight: 800; }.landing nav { display: flex; align-items: center; gap: 1.25rem; font-size: .9rem; }.hero { min-height: 34rem; display: grid; place-items: center; align-content: center; text-align: center; background: radial-gradient(circle, color-mix(in srgb, var(--ui-primary) 12%, transparent), transparent 55%); }.hero h1 { max-width: 13ch; font-size: clamp(3rem, 8vw, 6rem); line-height: .98; letter-spacing: -.06em; font-weight: 800; }.hero p { max-width: 42rem; font-size: 1.15rem; color: var(--ui-text-muted); }.hero > * + * { margin-top: 1.3rem; }.hero-actions { display: flex; gap: .75rem; }.product-shot { margin: 0 0 5rem; }.product-shot img { width: 100%; height: auto; border: 1px solid var(--ui-border); border-radius: 1.25rem; box-shadow: 0 2rem 5rem color-mix(in srgb, var(--ui-primary) 12%, transparent); }.product-shot figcaption { margin-top: .8rem; color: var(--ui-text-muted); text-align: center; font-size: .85rem; }.workflow { display: grid; grid-template-columns: repeat(5, 1fr); gap: .75rem; padding: 3rem 0; border-block: 1px solid var(--ui-border); }.workflow div { display: grid; gap: .5rem; }.workflow span { color: var(--ui-primary); font-weight: 700; }.eyebrow { color: var(--ui-primary); font-weight: 700; }#modules { padding: 6rem 0; }#modules h2 { max-width: 20ch; margin: .5rem 0 2rem; font-size: clamp(2rem, 4vw, 3.2rem); font-weight: 750; letter-spacing: -.04em; }.feature-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 1rem; }.feature-grid article { padding: 1.5rem; border: 1px solid var(--ui-border); border-radius: 1rem; background: var(--ui-bg-elevated); }.feature-mark { font-family: var(--font-mono); font-size: 1.4rem; }.feature-grid h3 { margin-top: 2rem; font-weight: 700; }.feature-grid p, footer { color: var(--ui-text-muted); }footer { padding: 2rem 0; border-top: 1px solid var(--ui-border); }
@media (max-width: 700px) { .landing nav a { display: none; }.workflow, .feature-grid { grid-template-columns: 1fr; }.workflow { gap: 1.5rem; }.hero-actions { flex-direction: column; } }
</style>
