<script setup lang="ts">
import { capturedResourcePath } from '../quick-capture.meta'
import type { CreatedResourceReference } from '../quick-capture.types'
const emit = defineEmits<{ dirty: [value: boolean]; pending: [value: boolean]; created: [value: CreatedResourceReference] }>()
const api = useApi(); const toast = useToast(); const state = reactive({ title: '', content: '' }); const pending = ref(false); const errors = ref<Record<string, string[]>>({}); const formError = ref('')
watch(state, () => emit('dirty', Boolean(state.title || state.content)), { deep: true })
async function submit() { if (pending.value) return; if (!state.title.trim()) { errors.value = { title: ['Title is required.'] }; return } pending.value = true; emit('pending', true); errors.value = {}; formError.value = ''; try { const created = await api.post<{ id: string; title: string; updatedAtUtc: string }>('/knowledge-nodes', { title: state.title.trim(), parentId: null }); if (state.content.trim()) await api.put(`/knowledge-nodes/${created.id}/content`, { content: state.content, expectedUpdatedAtUtc: created.updatedAtUtc }); toast.add({ title: 'Knowledge captured', color: 'success' }); emit('created', { id: created.id, title: created.title, targetPath: capturedResourcePath('KnowledgeNode', created.id) }) } catch (error) { const normalized = normalizeApiError(error); errors.value = normalized.fieldErrors; formError.value = normalized.detail ?? normalized.title } finally { pending.value = false; emit('pending', false) } }
</script>
<template><form class="grid gap-4" @submit.prevent="submit"><UFormField label="Title" required :error="errors.title?.[0]"><UInput v-model="state.title" autofocus class="w-full" /></UFormField><UFormField label="Content" :error="errors.content?.[0]"><UTextarea v-model="state.content" :rows="10" class="w-full" /></UFormField><p v-if="formError" role="alert" class="text-sm text-error">{{ formError }}</p><UButton type="submit" label="Create knowledge" block :loading="pending" :disabled="pending" /></form></template>
